name: node.js CI

on:
  push:
    branches:
      - "feature/**"
      - "hotfixes"
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm ci
          echo "::set-output name=cache-hit::$CACHE_HIT"

        env:
          CACHE_NAME: cache-node-modules
          CACHE_KEY: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          CACHE_HIT: ${{ steps.restore-cache.outputs.cache-hit }}

      - name: Restore Cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ env.CACHE_NAME }}-${{ runner.os }}-build-
            ${{ env.CACHE_NAME }}-${{ runner.os }}-
            ${{ env.CACHE_NAME }}-

      - name: Build Packages
        run: npm run build
